#!/bin/bash
# HookProbe Guardian SDN Setup Script
# Configures Raspberry Pi 4/5 as a VLAN-aware Access Point
# Version: 5.0.0

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$(dirname "$SCRIPT_DIR")/config"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

# Detect Raspberry Pi model
detect_pi_model() {
    if grep -q "Raspberry Pi 5" /proc/cpuinfo 2>/dev/null; then
        echo "pi5"
    elif grep -q "Raspberry Pi 4" /proc/cpuinfo 2>/dev/null; then
        echo "pi4"
    else
        echo "unknown"
    fi
}

PI_MODEL=$(detect_pi_model)
log_info "Detected Raspberry Pi model: $PI_MODEL"

# ============================================
# Install required packages
# ============================================
log_info "Installing required packages..."
apt-get update
apt-get install -y \
    hostapd \
    dnsmasq \
    bridge-utils \
    vlan \
    iw \
    wireless-tools \
    wpasupplicant \
    iptables \
    nftables \
    python3-flask \
    python3-requests \
    freeradius \
    freeradius-rest

# ============================================
# Enable VLAN kernel module
# ============================================
log_info "Enabling VLAN support..."
modprobe 8021q
echo "8021q" >> /etc/modules

# ============================================
# Stop services during configuration
# ============================================
log_info "Stopping services..."
systemctl stop hostapd 2>/dev/null || true
systemctl stop dnsmasq 2>/dev/null || true
systemctl stop wpa_supplicant 2>/dev/null || true

# ============================================
# Configure network interfaces
# ============================================
log_info "Configuring network interfaces..."

cat > /etc/network/interfaces.d/guardian-vlans << 'EOF'
# HookProbe Guardian VLAN Configuration
# Auto-generated by setup script

# Loopback
auto lo
iface lo inet loopback

# Ethernet (LAN port) - Management
auto eth0
iface eth0 inet manual

# Main bridge (Management VLAN)
auto br0
iface br0 inet static
    address 192.168.1.1
    netmask 255.255.255.0
    bridge_ports eth0
    bridge_stp off
    bridge_fd 0

# VLAN 10 - Smart Lights
auto eth0.10
iface eth0.10 inet manual
    vlan-raw-device eth0

auto br10
iface br10 inet static
    address 192.168.10.1
    netmask 255.255.255.0
    bridge_ports eth0.10
    bridge_stp off
    bridge_fd 0

# VLAN 20 - Thermostats
auto eth0.20
iface eth0.20 inet manual
    vlan-raw-device eth0

auto br20
iface br20 inet static
    address 192.168.20.1
    netmask 255.255.255.0
    bridge_ports eth0.20
    bridge_stp off
    bridge_fd 0

# VLAN 30 - Cameras
auto eth0.30
iface eth0.30 inet manual
    vlan-raw-device eth0

auto br30
iface br30 inet static
    address 192.168.30.1
    netmask 255.255.255.0
    bridge_ports eth0.30
    bridge_stp off
    bridge_fd 0

# VLAN 40 - Voice Assistants
auto eth0.40
iface eth0.40 inet manual
    vlan-raw-device eth0

auto br40
iface br40 inet static
    address 192.168.40.1
    netmask 255.255.255.0
    bridge_ports eth0.40
    bridge_stp off
    bridge_fd 0

# VLAN 50 - Appliances
auto eth0.50
iface eth0.50 inet manual
    vlan-raw-device eth0

auto br50
iface br50 inet static
    address 192.168.50.1
    netmask 255.255.255.0
    bridge_ports eth0.50
    bridge_stp off
    bridge_fd 0

# VLAN 60 - Entertainment
auto eth0.60
iface eth0.60 inet manual
    vlan-raw-device eth0

auto br60
iface br60 inet static
    address 192.168.60.1
    netmask 255.255.255.0
    bridge_ports eth0.60
    bridge_stp off
    bridge_fd 0

# VLAN 70 - Robots
auto eth0.70
iface eth0.70 inet manual
    vlan-raw-device eth0

auto br70
iface br70 inet static
    address 192.168.70.1
    netmask 255.255.255.0
    bridge_ports eth0.70
    bridge_stp off
    bridge_fd 0

# VLAN 80 - Sensors
auto eth0.80
iface eth0.80 inet manual
    vlan-raw-device eth0

auto br80
iface br80 inet static
    address 192.168.80.1
    netmask 255.255.255.0
    bridge_ports eth0.80
    bridge_stp off
    bridge_fd 0

# VLAN 999 - Quarantine
auto eth0.999
iface eth0.999 inet manual
    vlan-raw-device eth0

auto br999
iface br999 inet static
    address 192.168.99.1
    netmask 255.255.255.0
    bridge_ports eth0.999
    bridge_stp off
    bridge_fd 0
EOF

# ============================================
# Copy configuration files
# ============================================
log_info "Installing configuration files..."

# hostapd
mkdir -p /etc/hostapd
cp "$CONFIG_DIR/hostapd.conf" /etc/hostapd/hostapd.conf
cp "$CONFIG_DIR/hostapd.vlan" /etc/hostapd/hostapd.vlan
touch /etc/hostapd/hostapd.accept
touch /etc/hostapd/hostapd.deny

# Set hostapd config path
echo 'DAEMON_CONF="/etc/hostapd/hostapd.conf"' > /etc/default/hostapd

# dnsmasq
cp "$CONFIG_DIR/dnsmasq.conf" /etc/dnsmasq.d/guardian.conf

# wpa_supplicant (for upstream connection)
cp "$CONFIG_DIR/wpa_supplicant.conf" /etc/wpa_supplicant/wpa_supplicant-wlan1.conf

# ============================================
# Configure IP forwarding and NAT
# ============================================
log_info "Configuring IP forwarding..."

# Enable IP forwarding
echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-guardian.conf
sysctl -p /etc/sysctl.d/99-guardian.conf

# ============================================
# Configure iptables for VLAN isolation
# ============================================
log_info "Configuring firewall rules..."

cat > /etc/nftables.d/guardian-vlans.nft << 'EOF'
#!/usr/sbin/nft -f
# HookProbe Guardian - VLAN Isolation Rules

table inet guardian {
    chain forward {
        type filter hook forward priority 0; policy drop;

        # Allow established connections
        ct state established,related accept

        # Allow management VLAN (br0) to access internet
        iifname "br0" oifname "wlan1" accept
        iifname "wlan1" oifname "br0" accept

        # Allow each VLAN to access internet (via upstream wlan1)
        # But NOT to other VLANs
        iifname "br10" oifname "wlan1" accept
        iifname "br20" oifname "wlan1" accept
        iifname "br30" oifname "wlan1" accept
        iifname "br40" oifname "wlan1" accept
        iifname "br50" oifname "wlan1" accept
        iifname "br60" oifname "wlan1" accept
        iifname "br70" oifname "wlan1" accept
        iifname "br80" oifname "wlan1" accept

        # Allow return traffic from internet
        iifname "wlan1" ct state established,related accept

        # Quarantine VLAN - NO internet access
        # (devices must be registered first)
        iifname "br999" drop

        # Log and drop everything else
        log prefix "GUARDIAN-DROP: " drop
    }

    chain nat_postrouting {
        type nat hook postrouting priority 100;

        # NAT for outgoing traffic to upstream
        oifname "wlan1" masquerade
    }
}
EOF

# ============================================
# Create systemd service for Guardian
# ============================================
log_info "Creating Guardian service..."

cat > /etc/systemd/system/guardian-sdn.service << 'EOF'
[Unit]
Description=HookProbe Guardian SDN Service
After=network.target hostapd.service
Wants=hostapd.service

[Service]
Type=simple
ExecStart=/usr/local/bin/guardian-sdn-agent
Restart=always
RestartSec=5
User=root

[Install]
WantedBy=multi-user.target
EOF

# ============================================
# Create local web UI service
# ============================================
log_info "Creating Guardian local web UI..."

mkdir -p /opt/hookprobe/guardian
cp -r "$SCRIPT_DIR/../web/"* /opt/hookprobe/guardian/ 2>/dev/null || true

cat > /etc/systemd/system/guardian-webui.service << 'EOF'
[Unit]
Description=HookProbe Guardian Web UI
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/hookprobe/guardian
ExecStart=/usr/bin/python3 -m flask run --host=0.0.0.0 --port=8080
Environment=FLASK_APP=app.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

# ============================================
# Enable services
# ============================================
log_info "Enabling services..."

systemctl unmask hostapd
systemctl enable hostapd
systemctl enable dnsmasq
systemctl enable guardian-sdn
systemctl enable guardian-webui
systemctl enable nftables

# ============================================
# Final setup
# ============================================
log_info "Applying network configuration..."
systemctl restart networking || true

log_info ""
log_info "============================================"
log_info "HookProbe Guardian SDN Setup Complete!"
log_info "============================================"
log_info ""
log_info "Next steps:"
log_info "1. Edit /etc/hostapd/hostapd.conf to set your hotspot password"
log_info "2. Edit /etc/wpa_supplicant/wpa_supplicant-wlan1.conf for upstream WiFi"
log_info "3. Reboot the Raspberry Pi"
log_info "4. Access web UI at http://192.168.1.1:8080"
log_info ""
log_info "Default VLANs configured:"
log_info "  VLAN 10  - Smart Lights    (192.168.10.0/24)"
log_info "  VLAN 20  - Thermostats     (192.168.20.0/24)"
log_info "  VLAN 30  - Cameras         (192.168.30.0/24)"
log_info "  VLAN 40  - Voice Assistants(192.168.40.0/24)"
log_info "  VLAN 50  - Appliances      (192.168.50.0/24)"
log_info "  VLAN 60  - Entertainment   (192.168.60.0/24)"
log_info "  VLAN 70  - Robots          (192.168.70.0/24)"
log_info "  VLAN 80  - Sensors         (192.168.80.0/24)"
log_info "  VLAN 999 - Quarantine      (192.168.99.0/24)"
log_info ""
