# Generated by Django 5.1.15 on 2026-01-20 09:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="device_hub", max_length=32)),
                ("color", models.CharField(default="#607D8B", max_length=7)),
                (
                    "default_vlan",
                    models.PositiveIntegerField(
                        help_text="Default VLAN ID for devices in this category",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4094),
                        ],
                    ),
                ),
                (
                    "allow_internet",
                    models.BooleanField(
                        default=False, help_text="Allow internet access"
                    ),
                ),
                (
                    "allow_local_network",
                    models.BooleanField(
                        default=False, help_text="Allow access to local network"
                    ),
                ),
                (
                    "isolate_clients",
                    models.BooleanField(
                        default=True, help_text="Isolate clients from each other"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Device categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GuardianConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("upstream_ssid", models.CharField(blank=True, max_length=32)),
                ("upstream_password", models.CharField(blank=True, max_length=64)),
                (
                    "upstream_security",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("wpa2", "WPA2-PSK"),
                            ("wpa3", "WPA3-SAE"),
                            ("wpa2_enterprise", "WPA2-Enterprise"),
                        ],
                        default="wpa2",
                        max_length=16,
                    ),
                ),
                ("upstream_connected", models.BooleanField(default=False)),
                (
                    "hotspot_ssid",
                    models.CharField(default="HookProbe-Guardian", max_length=32),
                ),
                ("hotspot_password", models.CharField(max_length=64)),
                ("hotspot_channel", models.PositiveIntegerField(default=6)),
                (
                    "hotspot_band",
                    models.CharField(
                        choices=[
                            ("2.4GHz", "2.4 GHz"),
                            ("5GHz", "5 GHz"),
                            ("dual", "Dual Band"),
                        ],
                        default="dual",
                        max_length=8,
                    ),
                ),
                (
                    "bridge_lan",
                    models.BooleanField(
                        default=True, help_text="Bridge LAN port to network"
                    ),
                ),
                (
                    "bridge_upstream",
                    models.BooleanField(
                        default=True, help_text="Bridge to upstream WiFi"
                    ),
                ),
                ("radius_server", models.GenericIPAddressField(default="127.0.0.1")),
                (
                    "radius_secret",
                    models.CharField(default="hookprobe_radius", max_length=64),
                ),
                ("radius_port", models.PositiveIntegerField(default=1812)),
                ("management_vlan", models.PositiveIntegerField(default=1)),
                (
                    "quarantine_vlan",
                    models.PositiveIntegerField(
                        default=999, help_text="VLAN for unknown/unregistered devices"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_config_push", models.DateTimeField(blank=True, null=True)),
                ("config_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guardian",
                    models.OneToOneField(
                        limit_choices_to={"device_type": "guardian"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdn_config",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardian Configuration",
                "verbose_name_plural": "Guardian Configurations",
            },
        ),
        migrations.CreateModel(
            name="NetworkScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ssid", models.CharField(max_length=32)),
                ("bssid", models.CharField(max_length=17)),
                ("channel", models.PositiveIntegerField()),
                (
                    "signal_strength",
                    models.IntegerField(help_text="Signal strength in dBm"),
                ),
                ("security", models.CharField(max_length=32)),
                (
                    "frequency",
                    models.PositiveIntegerField(help_text="Frequency in MHz"),
                ),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_scans",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-signal_strength"],
            },
        ),
        migrations.CreateModel(
            name="VLAN",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vlan_id",
                    models.PositiveIntegerField(
                        help_text="VLAN ID (1-4094)",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4094),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "subnet",
                    models.CharField(
                        help_text="CIDR notation, e.g., 192.168.10.0/24", max_length=18
                    ),
                ),
                (
                    "gateway",
                    models.GenericIPAddressField(
                        help_text="Gateway IP address", protocol="IPv4"
                    ),
                ),
                (
                    "dhcp_start",
                    models.GenericIPAddressField(
                        help_text="DHCP range start", protocol="IPv4"
                    ),
                ),
                (
                    "dhcp_end",
                    models.GenericIPAddressField(
                        help_text="DHCP range end", protocol="IPv4"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vlans",
                        to="sdn.devicecategory",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"device_type": "guardian"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vlans",
                        to="devices.device",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vlans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "VLAN",
                "verbose_name_plural": "VLANs",
                "ordering": ["vlan_id"],
            },
        ),
        migrations.CreateModel(
            name="RegisteredDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        help_text="MAC address in format XX:XX:XX:XX:XX:XX",
                        max_length=17,
                    ),
                ),
                ("hostname", models.CharField(blank=True, max_length=64)),
                (
                    "friendly_name",
                    models.CharField(
                        help_text="User-friendly device name", max_length=128
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False, help_text="Block device from network"
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("manufacturer", models.CharField(blank=True, max_length=128)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="sdn.devicecategory",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"device_type": "guardian"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_clients",
                        to="devices.device",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vlan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific VLAN assignment (overrides category default)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="sdn.vlan",
                    ),
                ),
            ],
            options={
                "ordering": ["friendly_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mac_address", "owner"), name="unique_mac_per_owner"
                    )
                ],
            },
        ),
    ]
