#!/bin/bash
#
# HookProbe Fortress - Container Management Script
#
# Manages the complete containerized Fortress deployment.
# Self-contained, modular, and fully removable.
#
# Usage:
#   ./fortress-containers.sh start       # Start all containers
#   ./fortress-containers.sh stop        # Stop all containers
#   ./fortress-containers.sh status      # Show status
#   ./fortress-containers.sh logs [svc]  # Show logs
#   ./fortress-containers.sh shell [svc] # Open shell in container
#   ./fortress-containers.sh uninstall   # Complete removal
#
# Version: 5.0.0
# License: AGPL-3.0

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Configuration
COMPOSE_FILE="${SCRIPT_DIR}/podman-compose.yml"
SECRETS_DIR="${SCRIPT_DIR}/secrets"
DATA_DIR="/opt/hookprobe/fortress/data"
CONFIG_DIR="/etc/hookprobe"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${CYAN}[STEP]${NC} $1"; }

# ============================================================
# PREREQUISITES CHECK
# ============================================================
check_prerequisites() {
    log_step "Checking prerequisites..."

    # Check for podman
    if ! command -v podman &>/dev/null; then
        log_error "Podman not found. Install with: apt install podman"
        exit 1
    fi

    # Check for podman-compose
    if ! command -v podman-compose &>/dev/null; then
        log_warn "podman-compose not found, trying pip install..."
        pip3 install podman-compose 2>/dev/null || {
            log_error "Could not install podman-compose"
            exit 1
        }
    fi

    log_info "Prerequisites OK"
}

# ============================================================
# SECRETS MANAGEMENT
# ============================================================
setup_secrets() {
    log_step "Setting up secrets..."

    mkdir -p "$SECRETS_DIR"
    chmod 700 "$SECRETS_DIR"

    # Generate PostgreSQL password
    if [ ! -f "$SECRETS_DIR/postgres_password" ]; then
        openssl rand -base64 32 | tr -d '/+=' | head -c 32 > "$SECRETS_DIR/postgres_password"
        chmod 600 "$SECRETS_DIR/postgres_password"
        log_info "Generated PostgreSQL password"
    fi

    # Generate Flask secret key
    if [ ! -f "$SECRETS_DIR/flask_secret" ]; then
        openssl rand -base64 48 | tr -d '/+=' | head -c 48 > "$SECRETS_DIR/flask_secret"
        chmod 600 "$SECRETS_DIR/flask_secret"
        log_info "Generated Flask secret key"
    fi

    # Generate Redis password (optional)
    if [ ! -f "$SECRETS_DIR/redis_password" ]; then
        openssl rand -base64 24 | tr -d '/+=' | head -c 24 > "$SECRETS_DIR/redis_password"
        chmod 600 "$SECRETS_DIR/redis_password"
        log_info "Generated Redis password"
    fi

    log_info "Secrets initialized"
}

# ============================================================
# CONFIGURATION SETUP
# ============================================================
setup_config() {
    log_step "Setting up configuration..."

    mkdir -p "$CONFIG_DIR"
    chmod 755 "$CONFIG_DIR"

    # Create default Fortress config if not exists
    if [ ! -f "$CONFIG_DIR/fortress.conf" ]; then
        cat > "$CONFIG_DIR/fortress.conf" << 'EOF'
# HookProbe Fortress Configuration
# Generated by fortress-containers.sh

# Deployment mode
FORTRESS_MODE=container
FORTRESS_VERSION=5.0.0

# Network mode (vlan or filter)
# - vlan: Use OVS VLANs for segmentation (requires OVS setup)
# - filter: Use nftables/iptables for per-device filtering (simpler)
NETWORK_MODE=filter

# Database (handled by container)
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_NAME=fortress
DATABASE_USER=fortress

# Redis (handled by container)
REDIS_HOST=redis
REDIS_PORT=6379

# Web UI
WEB_PORT=8443
WEB_SSL=true

# Logging
LOG_LEVEL=info
LOG_DIR=/var/log/fortress
EOF
        log_info "Created default fortress.conf"
    fi

    log_info "Configuration ready"
}

# ============================================================
# BUILD CONTAINERS
# ============================================================
build_containers() {
    log_step "Building container images..."

    cd "$SCRIPT_DIR"

    # Build web container
    log_info "Building fortress-web image..."
    podman build -f Containerfile.web -t localhost/fortress-web:latest "$PROJECT_ROOT"

    log_info "Container images built"
}

# ============================================================
# START CONTAINERS
# ============================================================
start_containers() {
    log_step "Starting Fortress containers..."

    check_prerequisites
    setup_secrets
    setup_config

    cd "$SCRIPT_DIR"

    # Build if images don't exist
    if ! podman image exists localhost/fortress-web:latest; then
        build_containers
    fi

    # Start with podman-compose
    podman-compose -f "$COMPOSE_FILE" up -d

    # Wait for services to be healthy
    log_info "Waiting for services to be ready..."
    sleep 5

    # Check health
    local retries=30
    while [ $retries -gt 0 ]; do
        if curl -sf -k https://localhost:8443/health &>/dev/null; then
            log_info "Web service is healthy"
            break
        fi
        sleep 2
        ((retries--))
    done

    if [ $retries -eq 0 ]; then
        log_warn "Web service may not be fully ready - check logs"
    fi

    show_status
    echo ""
    log_info "Fortress is ready!"
    log_info "Access admin portal at: https://localhost:8443"
    log_info "Default login: admin / hookprobe (CHANGE THIS!)"
}

# ============================================================
# STOP CONTAINERS
# ============================================================
stop_containers() {
    log_step "Stopping Fortress containers..."

    cd "$SCRIPT_DIR"
    podman-compose -f "$COMPOSE_FILE" down

    log_info "Containers stopped"
}

# ============================================================
# SHOW STATUS
# ============================================================
show_status() {
    echo ""
    echo "=== Fortress Container Status ==="
    echo ""

    cd "$SCRIPT_DIR"
    podman-compose -f "$COMPOSE_FILE" ps

    echo ""
    echo "=== Volume Status ==="
    podman volume ls --filter name=fortress

    echo ""
    echo "=== Health Checks ==="

    # Check web
    if curl -sf -k https://localhost:8443/health &>/dev/null; then
        echo -e "Web:      ${GREEN}HEALTHY${NC}"
    else
        echo -e "Web:      ${RED}UNHEALTHY${NC}"
    fi

    # Check PostgreSQL
    if podman exec fortress-postgres pg_isready -U fortress &>/dev/null; then
        echo -e "Database: ${GREEN}HEALTHY${NC}"
    else
        echo -e "Database: ${RED}UNHEALTHY${NC}"
    fi

    # Check Redis
    if podman exec fortress-redis redis-cli ping &>/dev/null; then
        echo -e "Redis:    ${GREEN}HEALTHY${NC}"
    else
        echo -e "Redis:    ${RED}UNHEALTHY${NC}"
    fi

    echo ""
}

# ============================================================
# SHOW LOGS
# ============================================================
show_logs() {
    local service="${1:-web}"
    local lines="${2:-100}"

    cd "$SCRIPT_DIR"

    case "$service" in
        web|fortress-web)
            podman logs -f --tail "$lines" fortress-web
            ;;
        postgres|db|database)
            podman logs -f --tail "$lines" fortress-postgres
            ;;
        redis|cache)
            podman logs -f --tail "$lines" fortress-redis
            ;;
        all)
            podman-compose -f "$COMPOSE_FILE" logs -f --tail "$lines"
            ;;
        *)
            log_error "Unknown service: $service"
            echo "Available: web, postgres, redis, all"
            exit 1
            ;;
    esac
}

# ============================================================
# SHELL ACCESS
# ============================================================
shell_access() {
    local service="${1:-web}"

    case "$service" in
        web|fortress-web)
            podman exec -it fortress-web /bin/bash
            ;;
        postgres|db|database)
            podman exec -it fortress-postgres /bin/sh
            ;;
        redis|cache)
            podman exec -it fortress-redis /bin/sh
            ;;
        psql)
            podman exec -it fortress-postgres psql -U fortress -d fortress
            ;;
        *)
            log_error "Unknown service: $service"
            echo "Available: web, postgres, redis, psql"
            exit 1
            ;;
    esac
}

# ============================================================
# DATABASE BACKUP
# ============================================================
backup_database() {
    local backup_dir="${1:-/opt/hookprobe/fortress/backups}"
    local timestamp=$(date +%Y%m%d_%H%M%S)
    local backup_file="${backup_dir}/fortress_${timestamp}.sql.gz"

    mkdir -p "$backup_dir"

    log_step "Backing up database to $backup_file..."

    podman exec fortress-postgres pg_dump -U fortress fortress | gzip > "$backup_file"

    log_info "Backup completed: $backup_file"
    log_info "Size: $(du -h "$backup_file" | cut -f1)"
}

# ============================================================
# DATABASE RESTORE
# ============================================================
restore_database() {
    local backup_file="$1"

    if [ -z "$backup_file" ]; then
        log_error "Usage: $0 restore <backup_file>"
        exit 1
    fi

    if [ ! -f "$backup_file" ]; then
        log_error "Backup file not found: $backup_file"
        exit 1
    fi

    log_step "Restoring database from $backup_file..."

    # Determine if gzipped
    if [[ "$backup_file" == *.gz ]]; then
        zcat "$backup_file" | podman exec -i fortress-postgres psql -U fortress -d fortress
    else
        cat "$backup_file" | podman exec -i fortress-postgres psql -U fortress -d fortress
    fi

    log_info "Database restored"
}

# ============================================================
# COMPLETE UNINSTALL
# ============================================================
uninstall() {
    log_step "Uninstalling Fortress containers..."

    echo ""
    echo -e "${RED}WARNING: This will remove:${NC}"
    echo "  - All Fortress containers"
    echo "  - All Fortress volumes (database, logs, data)"
    echo "  - Generated secrets"
    echo "  - Container images"
    echo ""
    echo "Configuration files in /etc/hookprobe will be preserved."
    echo ""
    read -p "Are you sure? (type 'yes' to confirm): " confirm

    if [ "$confirm" != "yes" ]; then
        log_info "Uninstall cancelled"
        exit 0
    fi

    cd "$SCRIPT_DIR"

    # Stop and remove containers
    log_info "Stopping containers..."
    podman-compose -f "$COMPOSE_FILE" down -v 2>/dev/null || true

    # Remove volumes
    log_info "Removing volumes..."
    podman volume rm fortress-postgres-data fortress-redis-data fortress-web-data fortress-web-logs fortress-agent-data fortress-config 2>/dev/null || true

    # Remove images
    log_info "Removing images..."
    podman rmi localhost/fortress-web:latest localhost/fortress-agent:latest 2>/dev/null || true

    # Remove secrets
    log_info "Removing secrets..."
    rm -rf "$SECRETS_DIR"

    # Remove data directory (but not config)
    log_info "Removing data directory..."
    rm -rf "$DATA_DIR"

    echo ""
    log_info "Uninstall complete!"
    log_info "Configuration preserved in: $CONFIG_DIR"
    log_info "To remove config: rm -rf $CONFIG_DIR"
}

# ============================================================
# MAIN
# ============================================================
usage() {
    echo "HookProbe Fortress Container Manager"
    echo ""
    echo "Usage: $0 <command> [options]"
    echo ""
    echo "Commands:"
    echo "  start           Start all Fortress containers"
    echo "  stop            Stop all containers"
    echo "  restart         Restart all containers"
    echo "  status          Show container status"
    echo "  logs [service]  Show logs (web, postgres, redis, all)"
    echo "  shell [service] Open shell in container (web, postgres, redis, psql)"
    echo "  build           Build container images"
    echo "  backup [dir]    Backup database"
    echo "  restore <file>  Restore database from backup"
    echo "  uninstall       Complete removal (containers, volumes, data)"
    echo ""
    echo "Examples:"
    echo "  $0 start              # Start Fortress"
    echo "  $0 logs web           # Follow web logs"
    echo "  $0 shell psql         # PostgreSQL shell"
    echo "  $0 backup             # Backup database"
    echo "  $0 uninstall          # Remove everything"
    echo ""
}

case "${1:-}" in
    start|up)
        start_containers
        ;;
    stop|down)
        stop_containers
        ;;
    restart)
        stop_containers
        start_containers
        ;;
    status|ps)
        show_status
        ;;
    logs)
        show_logs "${2:-all}" "${3:-100}"
        ;;
    shell|exec)
        shell_access "${2:-web}"
        ;;
    build)
        check_prerequisites
        build_containers
        ;;
    backup)
        backup_database "${2:-}"
        ;;
    restore)
        restore_database "${2:-}"
        ;;
    uninstall|remove)
        uninstall
        ;;
    *)
        usage
        ;;
esac
