# HookProbe Fortress - Mesh Orchestrator (Optional)
#
# This file contains the mesh-orchestrator service which provides
# HTP/Neuro/DSM communication for federation with other HookProbe products.
#
# Usage:
#   podman-compose -f podman-compose.yml -f podman-compose.mesh.yml up -d mesh-orchestrator
#
# Or to start all services including mesh:
#   podman-compose -f podman-compose.yml -f podman-compose.mesh.yml up -d
#
# NOTE: This is separate from the main compose file because podman-compose 1.x
# doesn't properly support profiles. With docker-compose 2.x, you could use
# --profile mesh instead.
#
# Version: 5.5.0
# License: AGPL-3.0

version: '3.8'

services:
  # ============================================================
  # MESH TIER - Inter-Product Communication (HTP/Neuro/DSM)
  # ============================================================

  # Mesh Orchestrator - HTP/Neuro/DSM Communication Hub
  # Enables secure mesh communication with Guardian, Sentinel, Nexus, MSSP
  # Port Selection (from shared/mesh/ARCHITECTURE.md):
  #   PRIMARY:   8144/UDP + 8144/TCP (HTP native)
  #   FALLBACK:  8543/UDP + 8543/TCP (TLS-wrapped, avoids web UI 8443 conflict)
  #   STEALTH:   8853/UDP + 8853/TCP (DoT/DoQ cover, 853 used by dnsXai DoT)
  #   RELAY:     3478/UDP (STUN/TURN for NAT traversal)
  mesh-orchestrator:
    build:
      context: ../..
      dockerfile: products/fortress/containers/Containerfile.mesh
    image: localhost/fts-mesh:latest
    container_name: fts-mesh
    restart: unless-stopped
    hostname: fts-mesh
    environment:
      # Mesh identity
      MESH_NODE_ID: "${MESH_NODE_ID:-fortress-${HOSTNAME:-node}}"
      MESH_NODE_TYPE: fortress
      MESH_DATA_DIR: /opt/hookprobe/mesh/data
      # HTP configuration
      HTP_PRIMARY_PORT: 8144
      HTP_FALLBACK_PORT: 8543
      HTP_STEALTH_PORT: 8853
      HTP_RELAY_PORT: 3478
      # Neuro configuration
      NEURO_WEIGHT_DIR: /opt/hookprobe/mesh/neuro
      NEURO_DRIFT_THRESHOLD: 0.05
      # DSM configuration
      DSM_ENABLED: "true"
      DSM_CONSENSUS_QUORUM: 0.67
      DSM_CHECKPOINT_INTERVAL: 300
      # Peer discovery (comma-separated list of known peers)
      MESH_BOOTSTRAP_PEERS: "${MESH_BOOTSTRAP_PEERS:-}"
      # MSSP uplink (optional)
      MSSP_ENDPOINT: "${MSSP_ENDPOINT:-}"
      MSSP_API_KEY: "${MSSP_API_KEY:-}"
      # Integration with local services
      QSECBIT_API_URL: http://localhost:9090
      DNSXAI_API_URL: http://fts-dnsxai:8080
      # Cortex visualization bridge
      CORTEX_ENABLED: "true"
      CORTEX_WS_PORT: 8766
    volumes:
      - mesh_data:/opt/hookprobe/mesh/data
      - mesh_neuro:/opt/hookprobe/mesh/neuro
      - /etc/hookprobe:/etc/hookprobe:ro
    ports:
      # HTP Primary (UDP-first design for low-latency mesh)
      - "0.0.0.0:8144:8144/udp"
      - "0.0.0.0:8144:8144/tcp"
      # HTP Fallback (TLS-wrapped, 8543 to avoid conflict with web UI on 8443)
      - "0.0.0.0:8543:8543/udp"
      - "0.0.0.0:8543:8543/tcp"
      # HTP Stealth (DoT/DoQ cover traffic, port 853 used by dnsXai for real DoT)
      - "0.0.0.0:8853:8853/udp"
      - "0.0.0.0:8853:8853/tcp"
      # STUN/TURN Relay for NAT traversal
      - "0.0.0.0:3478:3478/udp"
      # Cortex WebSocket (local only)
      - "127.0.0.1:8766:8766"
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8766/health\", timeout=5)'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      fts-internal:
        ipv4_address: 172.20.200.70
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

# Mesh volumes (only used when mesh is enabled)
volumes:
  mesh_data:
    driver: local
    name: fts-mesh-data
  mesh_neuro:
    driver: local
    name: fts-mesh-neuro

# Use the same network as main compose file
networks:
  fts-internal:
    external: true
    name: fts-internal
