# Generated by Django 5.1.15 on 2026-01-20 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("signature", "Signature-based"),
                            ("behavioral", "Behavioral/ML"),
                            ("threshold", "Threshold-based"),
                            ("correlation", "Correlation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pattern",
                    models.TextField(
                        help_text="Regex pattern or ML feature definition"
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(default=0.8, help_text="Detection threshold"),
                ),
                (
                    "window_seconds",
                    models.IntegerField(
                        default=60, help_text="Time window for correlation"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attack_type", models.CharField(max_length=100)),
                ("mitre_tactic", models.CharField(blank=True, max_length=100)),
                ("mitre_technique", models.CharField(blank=True, max_length=100)),
                ("auto_quarantine", models.BooleanField(default=False)),
                ("quarantine_duration_minutes", models.IntegerField(default=60)),
                ("min_confidence_for_quarantine", models.FloatField(default=0.9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("testing", "Testing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hit_count", models.IntegerField(default=0)),
                ("false_positive_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Detection Rule",
                "verbose_name_plural": "Detection Rules",
                "ordering": ["-hit_count"],
            },
        ),
        migrations.CreateModel(
            name="QsecbitScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("score", models.FloatField()),
                (
                    "rag_status",
                    models.CharField(
                        choices=[
                            ("GREEN", "Green"),
                            ("AMBER", "Amber"),
                            ("RED", "Red"),
                        ],
                        max_length=10,
                    ),
                ),
                ("attack_probability", models.FloatField()),
                ("drift", models.FloatField()),
                ("classifier_decay", models.FloatField()),
                ("quantum_drift", models.FloatField()),
                ("energy_anomaly", models.FloatField(blank=True, null=True)),
                ("components", models.JSONField()),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Qsecbit Score",
                "verbose_name_plural": "Qsecbit Scores",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="security_qs_timesta_9e8f1f_idx"
                    ),
                    models.Index(
                        fields=["rag_status", "-timestamp"],
                        name="security_qs_rag_sta_544bd3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KaliResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("recommended_actions", models.JSONField()),
                ("executed_actions", models.JSONField(default=list)),
                ("results", models.JSONField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "qsecbit_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kali_responses",
                        to="security.qsecbitscore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kali Response",
                "verbose_name_plural": "Kali Responses",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=100, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("snort", "Snort 3"),
                            ("zeek", "Zeek"),
                            ("suricata", "Suricata"),
                            ("waf", "Web Application Firewall"),
                            ("qsecbit", "Qsecbit"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attack_type", models.CharField(max_length=100)),
                ("src_ip", models.GenericIPAddressField()),
                ("dst_ip", models.GenericIPAddressField()),
                ("src_port", models.IntegerField(blank=True, null=True)),
                ("dst_port", models.IntegerField(blank=True, null=True)),
                ("protocol", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField()),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Security Event",
                "verbose_name_plural": "Security Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="security_se_timesta_db5781_idx"
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="security_se_severit_88a96a_idx",
                    ),
                    models.Index(
                        fields=["src_ip"], name="security_se_src_ip_609e08_idx"
                    ),
                    models.Index(
                        fields=["attack_type", "-timestamp"],
                        name="security_se_attack__6e1bba_idx",
                    ),
                    models.Index(
                        fields=["source_type", "-timestamp"],
                        name="security_se_source__f5d98c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ThreatIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threat_type",
                    models.CharField(
                        choices=[
                            ("ip", "Malicious IP"),
                            ("domain", "Malicious Domain"),
                            ("hash", "Malicious Hash"),
                            ("cve", "CVE"),
                            ("signature", "Attack Signature"),
                        ],
                        max_length=20,
                    ),
                ),
                ("indicator", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(max_length=200)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Threat Intelligence",
                "verbose_name_plural": "Threat Intelligence",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["indicator"], name="security_th_indicat_583ee5_idx"
                    ),
                    models.Index(
                        fields=["threat_type", "-last_seen"],
                        name="security_th_threat__4772f2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuarantineAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_id", models.CharField(max_length=100, unique=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("block_ip", "Block IP Address"),
                            ("block_port", "Block Port"),
                            ("rate_limit", "Rate Limit"),
                            ("redirect", "Redirect to Honeypot"),
                            ("isolate", "Network Isolation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_ip", models.GenericIPAddressField()),
                ("target_port", models.IntegerField(blank=True, null=True)),
                ("protocol", models.CharField(default="all", max_length=20)),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("low", "Low (< 50%)"),
                            ("medium", "Medium (50-80%)"),
                            ("high", "High (80-95%)"),
                            ("critical", "Critical (> 95%)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("classification_method", models.CharField(max_length=50)),
                ("signature_match", models.CharField(blank=True, max_length=200)),
                ("ml_model_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("manual_release", "Manual Release"),
                            ("auto_release", "Auto Release"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("released_by", models.CharField(blank=True, max_length=100)),
                ("release_reason", models.TextField(blank=True)),
                ("nft_rule_handle", models.CharField(blank=True, max_length=50)),
                (
                    "security_event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quarantine_actions",
                        to="security.securityevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quarantine Action",
                "verbose_name_plural": "Quarantine Actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_ip"], name="security_qu_target__39d63b_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="security_qu_status_33a195_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="security_qu_action__7f26a2_idx",
                    ),
                    models.Index(
                        fields=["confidence_level", "-created_at"],
                        name="security_qu_confide_55a47b_idx",
                    ),
                ],
            },
        ),
    ]
