# Generated by Django 5.1.15 on 2026-01-20 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIContentDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True)),
                (
                    "ai_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("manual", "Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ai_model", models.CharField(blank=True, max_length=100)),
                (
                    "ai_confidence_score",
                    models.FloatField(
                        blank=True, help_text="AI confidence score (0-1)", null=True
                    ),
                ),
                (
                    "ai_prompt",
                    models.TextField(
                        blank=True, help_text="Prompt used for generation"
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                ("seo_description", models.TextField(blank=True, max_length=300)),
                ("seo_keywords", models.CharField(blank=True, max_length=500)),
                (
                    "seo_score",
                    models.IntegerField(default=0, help_text="SEO score (0-100)"),
                ),
                (
                    "research_sources",
                    models.JSONField(
                        default=list, help_text="List of URLs used for research"
                    ),
                ),
                ("research_summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("exported", "Exported to hookprobe.com"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "external_blog_id",
                    models.IntegerField(
                        blank=True, help_text="Blog post ID on hookprobe.com", null=True
                    ),
                ),
                (
                    "external_blog_url",
                    models.URLField(
                        blank=True, help_text="URL of published post on hookprobe.com"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_drafts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_drafts_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Content Draft",
                "verbose_name_plural": "AI Content Drafts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentResearchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("max_sources", models.IntegerField(default=10)),
                (
                    "include_cve",
                    models.BooleanField(
                        default=False, help_text="Include CVE database search"
                    ),
                ),
                (
                    "include_news",
                    models.BooleanField(
                        default=True, help_text="Include security news"
                    ),
                ),
                (
                    "include_blogs",
                    models.BooleanField(
                        default=True, help_text="Include security blogs"
                    ),
                ),
                (
                    "research_data",
                    models.JSONField(default=dict, help_text="Collected research data"),
                ),
                ("sources_found", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_dashboard.aicontentdraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Research Task",
                "verbose_name_plural": "Content Research Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="N8NWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("response_status", models.IntegerField()),
                ("response_data", models.JSONField(default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "related_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_dashboard.aicontentdraft",
                    ),
                ),
                (
                    "related_research",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_dashboard.contentresearchtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "n8n Webhook Log",
                "verbose_name_plural": "n8n Webhook Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
