# Generated by Django 5.1.15 on 2026-01-20 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("edge", "HookProbe Edge Node"),
                            ("validator", "DSM Validator"),
                            ("suricata", "Suricata IDS/IPS"),
                            ("zeek", "Zeek Network Monitor"),
                            ("openflow", "OpenFlow Switch"),
                            ("xdp", "XDP Packet Filter"),
                            ("ebpf", "eBPF Monitor"),
                            ("firewall", "Firewall"),
                            ("endpoint", "Endpoint Agent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                (
                    "hardware_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 of CPU+MAC+disk+DMI+hostname (no TPM required)",
                        max_length=64,
                    ),
                ),
                (
                    "public_key_ed25519",
                    models.CharField(
                        blank=True, help_text="Device Ed25519 public key", max_length=64
                    ),
                ),
                (
                    "neural_weight_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA512 of current neural weight state",
                        max_length=128,
                    ),
                ),
                (
                    "last_posf_signature",
                    models.CharField(
                        blank=True,
                        help_text="Last Proof-of-Sensor-Fusion signature",
                        max_length=64,
                    ),
                ),
                (
                    "weight_divergence_detected",
                    models.BooleanField(
                        default=False,
                        help_text="Offline tampering detected via weight mismatch",
                    ),
                ),
                (
                    "htp_session_active",
                    models.BooleanField(default=False, help_text="Active HTP session"),
                ),
                (
                    "last_htp_heartbeat",
                    models.DateTimeField(
                        blank=True, help_text="Last HTP heartbeat", null=True
                    ),
                ),
                (
                    "dsm_participant",
                    models.BooleanField(
                        default=False, help_text="Participating in DSM consensus"
                    ),
                ),
                (
                    "validator_id",
                    models.CharField(
                        blank=True, help_text="Managing validator ID", max_length=100
                    ),
                ),
                (
                    "kyc_verified",
                    models.BooleanField(
                        default=False, help_text="KYC verified (validators only)"
                    ),
                ),
                ("latitude", models.FloatField(help_text="Geographic latitude")),
                ("longitude", models.FloatField(help_text="Geographic longitude")),
                (
                    "location_name",
                    models.CharField(help_text="City, Country", max_length=200),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "asn",
                    models.IntegerField(
                        blank=True, help_text="Autonomous System Number", null=True
                    ),
                ),
                (
                    "isp",
                    models.CharField(
                        blank=True,
                        help_text="Internet Service Provider",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("degraded", "Degraded"),
                            ("maintenance", "Maintenance"),
                            ("quarantine", "Quarantine - Weight Divergence"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mssp_security_device",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorOfCompromise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ioc_type",
                    models.CharField(
                        choices=[
                            ("ip", "IP Address"),
                            ("domain", "Domain Name"),
                            ("url", "URL"),
                            ("email", "Email Address"),
                            ("file_hash", "File Hash (MD5/SHA256)"),
                            ("mac_address", "MAC Address"),
                            ("user_agent", "User Agent"),
                            ("certificate", "SSL Certificate"),
                            ("registry_key", "Registry Key"),
                            ("process", "Process Name"),
                            ("command", "Command Line"),
                            ("behavior", "Behavioral Pattern"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(help_text="The actual IoC value", max_length=500),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        max_length=10,
                    ),
                ),
                ("detected_by_qsecbit", models.BooleanField(default=False)),
                ("detected_by_openflow", models.BooleanField(default=False)),
                ("detected_by_suricata", models.BooleanField(default=False)),
                ("detected_by_snort", models.BooleanField(default=False)),
                ("detected_by_zeek", models.BooleanField(default=False)),
                ("detected_by_xdp", models.BooleanField(default=False)),
                ("detected_by_ebpf", models.BooleanField(default=False)),
                ("detected_by_siem", models.BooleanField(default=False)),
                ("detected_by_threat_intel", models.BooleanField(default=False)),
                (
                    "detection_count",
                    models.IntegerField(
                        default=0, help_text="Number of systems that detected this"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="0-100: Confidence this is malicious"
                    ),
                ),
                (
                    "qsecbit_score",
                    models.FloatField(
                        blank=True, help_text="QSECBIT threat score", null=True
                    ),
                ),
                (
                    "qsecbit_rag_status",
                    models.CharField(
                        blank=True, help_text="RED/AMBER/GREEN", max_length=10
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "occurrence_count",
                    models.IntegerField(default=1, help_text="How many times observed"),
                ),
                (
                    "source_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw data from detection sources",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_false_positive", models.BooleanField(default=False)),
                ("is_whitelisted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_iocs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_iocs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="correlations",
                        to="mssp_dashboard.indicatorofcompromise",
                    ),
                ),
                (
                    "affected_devices",
                    models.ManyToManyField(
                        related_name="detected_iocs", to="mssp_dashboard.securitydevice"
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator of Compromise",
                "verbose_name_plural": "Indicators of Compromise",
                "db_table": "mssp_indicator_of_compromise",
                "ordering": ["-severity", "-confidence_score", "-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="SecurityMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("alert", "Security Alert"),
                            ("connection", "Network Connection"),
                            ("packet", "Packet Count"),
                            ("bandwidth", "Bandwidth Usage"),
                            ("threat", "Threat Detection"),
                            ("anomaly", "Anomaly Detection"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField(help_text="Numeric metric value")),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g., 'count', 'Mbps', 'packets/sec'", max_length=20
                    ),
                ),
                (
                    "source_tool",
                    models.CharField(help_text="Suricata, Zeek, etc.", max_length=50),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="mssp_dashboard.securitydevice",
                    ),
                ),
            ],
            options={
                "db_table": "mssp_security_metric",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SOARPlaybook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("trigger_on_vulnerability", models.BooleanField(default=False)),
                ("trigger_on_alert", models.BooleanField(default=False)),
                ("trigger_severity", models.CharField(blank=True, max_length=10)),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text="Ordered list of automation steps"
                    ),
                ),
                (
                    "n8n_webhook_url",
                    models.URLField(blank=True, help_text="n8n webhook for automation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("execution_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_playbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mssp_soar_playbook",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Execution results and logs"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="mssp_dashboard.soarplaybook",
                    ),
                ),
            ],
            options={
                "db_table": "mssp_playbook_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreatIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "threat_type",
                    models.CharField(
                        choices=[
                            ("malware", "Malware"),
                            ("phishing", "Phishing"),
                            ("ransomware", "Ransomware"),
                            ("apt", "Advanced Persistent Threat"),
                            ("ddos", "DDoS Attack"),
                            ("data_breach", "Data Breach"),
                            ("zero_day", "Zero-Day Exploit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High Confidence"),
                            ("medium", "Medium Confidence"),
                            ("low", "Low Confidence"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "iocs",
                    models.JSONField(
                        default=list, help_text="IP addresses, domains, file hashes"
                    ),
                ),
                ("threat_actor", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(help_text="Intelligence source", max_length=200),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("references", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mssp_threat_intelligence",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["threat_type", "-published_at"],
                        name="mssp_threat_threat__d9f1cf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IoC_Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical Incident"),
                            ("high", "High Severity"),
                            ("medium", "Medium Severity"),
                            ("low", "Low Severity"),
                            ("info", "Informational"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active Investigation"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "incident_start",
                    models.DateTimeField(help_text="When the incident started"),
                ),
                (
                    "incident_end",
                    models.DateTimeField(
                        blank=True, help_text="When resolved", null=True
                    ),
                ),
                (
                    "attack_vector",
                    models.CharField(
                        blank=True, help_text="How the attack occurred", max_length=100
                    ),
                ),
                (
                    "attack_stages",
                    models.JSONField(
                        blank=True, default=list, help_text="Kill chain stages observed"
                    ),
                ),
                ("impact_assessment", models.TextField(blank=True)),
                ("data_exfiltrated", models.BooleanField(default=False)),
                ("systems_compromised", models.IntegerField(default=0)),
                ("threat_actor", models.CharField(blank=True, max_length=200)),
                (
                    "response_actions",
                    models.JSONField(
                        blank=True, default=list, help_text="Actions taken to respond"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations to prevent recurrence"
                    ),
                ),
                (
                    "overall_risk_score",
                    models.FloatField(
                        default=0.0, help_text="Aggregated risk score 0-100"
                    ),
                ),
                (
                    "qsecbit_analysis",
                    models.JSONField(
                        blank=True, default=dict, help_text="QSECBIT AI analysis"
                    ),
                ),
                (
                    "openflow_metrics",
                    models.JSONField(
                        blank=True, default=dict, help_text="OpenFlow SDN data"
                    ),
                ),
                (
                    "ids_alerts",
                    models.JSONField(
                        blank=True, default=dict, help_text="Suricata/Snort alerts"
                    ),
                ),
                (
                    "network_analysis",
                    models.JSONField(
                        blank=True, default=dict, help_text="Zeek network analysis"
                    ),
                ),
                (
                    "packet_analysis",
                    models.JSONField(
                        blank=True, default=dict, help_text="XDP/eBPF data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_ioc_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_ioc_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iocs",
                    models.ManyToManyField(
                        related_name="reports",
                        to="mssp_dashboard.indicatorofcompromise",
                    ),
                ),
                (
                    "playbooks_executed",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_reports",
                        to="mssp_dashboard.playbookexecution",
                    ),
                ),
                (
                    "affected_devices",
                    models.ManyToManyField(
                        related_name="ioc_reports", to="mssp_dashboard.securitydevice"
                    ),
                ),
                (
                    "related_threat_intel",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_reports",
                        to="mssp_dashboard.threatintelligence",
                    ),
                ),
            ],
            options={
                "verbose_name": "IoC Report",
                "verbose_name_plural": "IoC Reports",
                "db_table": "mssp_ioc_report",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="indicatorofcompromise",
            name="threat_intel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_iocs",
                to="mssp_dashboard.threatintelligence",
            ),
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        blank=True, help_text="CVE-2024-XXXXX", max_length=20
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "cvss_score",
                    models.FloatField(
                        blank=True, help_text="CVSS 3.1 score (0-10)", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("mitigated", "Mitigated"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_mitigation_recommendation",
                    models.TextField(
                        blank=True, help_text="AI-generated mitigation steps"
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.FloatField(
                        blank=True, help_text="AI confidence (0-1)", null=True
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="URLs to CVE databases, advisories",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_devices",
                    models.ManyToManyField(
                        related_name="vulnerabilities",
                        to="mssp_dashboard.securitydevice",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vulnerabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_vulnerabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vulnerabilities",
                "db_table": "mssp_vulnerability",
                "ordering": ["-severity", "-discovered_at"],
            },
        ),
        migrations.AddField(
            model_name="playbookexecution",
            name="vulnerability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playbook_executions",
                to="mssp_dashboard.vulnerability",
            ),
        ),
        migrations.AddIndex(
            model_name="securitydevice",
            index=models.Index(
                fields=["customer", "status"], name="mssp_securi_custome_cebdc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitydevice",
            index=models.Index(
                fields=["device_type"], name="mssp_securi_device__d72d79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitydevice",
            index=models.Index(
                fields=["-last_seen"], name="mssp_securi_last_se_bade56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitymetric",
            index=models.Index(
                fields=["device", "metric_type", "-timestamp"],
                name="mssp_securi_device__84abdf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitymetric",
            index=models.Index(
                fields=["severity", "-timestamp"], name="mssp_securi_severit_88083e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ioc_report",
            index=models.Index(
                fields=["customer", "status"], name="mssp_ioc_re_custome_a2d556_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ioc_report",
            index=models.Index(
                fields=["severity", "status"], name="mssp_ioc_re_severit_ed858f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ioc_report",
            index=models.Index(
                fields=["-created_at"], name="mssp_ioc_re_created_936968_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicatorofcompromise",
            index=models.Index(
                fields=["customer", "is_active"], name="mssp_indica_custome_4637b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicatorofcompromise",
            index=models.Index(
                fields=["ioc_type", "value"], name="mssp_indica_ioc_typ_c14c58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicatorofcompromise",
            index=models.Index(
                fields=["severity", "-confidence_score"],
                name="mssp_indica_severit_fabd63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indicatorofcompromise",
            index=models.Index(
                fields=["-last_seen"], name="mssp_indica_last_se_521e11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicatorofcompromise",
            index=models.Index(
                fields=["qsecbit_rag_status", "-last_seen"],
                name="mssp_indica_qsecbit_7cbffb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="indicatorofcompromise",
            unique_together={("customer", "ioc_type", "value")},
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(
                fields=["customer", "status"], name="mssp_vulner_custome_3c67ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(
                fields=["severity", "status"], name="mssp_vulner_severit_e41147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(
                fields=["-discovered_at"], name="mssp_vulner_discove_c7477f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playbookexecution",
            index=models.Index(
                fields=["playbook", "-started_at"],
                name="mssp_playbo_playboo_cade3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playbookexecution",
            index=models.Index(fields=["status"], name="mssp_playbo_status_06ecd2_idx"),
        ),
    ]
