name: 'Setup Python Environment'
description: 'Sets up Python with common dependencies for HookProbe testing'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  install-requirements:
    description: 'Whether to install requirements.txt'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install base dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint bandit black isort mypy

    - name: Install requirements.txt
      if: inputs.install-requirements == 'true'
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found, skipping"
        fi
