# Generated by Django 5.1.15 on 2026-01-20 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tenant_id", models.CharField(max_length=100, unique=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("hostname", models.CharField(max_length=200)),
                ("ip_address", models.GenericIPAddressField()),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                (
                    "hardware_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 of CPU+MAC+disk+DMI+hostname",
                        max_length=64,
                    ),
                ),
                (
                    "public_key_ed25519",
                    models.CharField(
                        blank=True,
                        help_text="Device Ed25519 public key for HTP authentication",
                        max_length=64,
                    ),
                ),
                (
                    "neural_weight_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="SHA512 of current neural weight state",
                        max_length=128,
                    ),
                ),
                (
                    "last_posf_signature",
                    models.CharField(
                        blank=True,
                        help_text="Last Proof-of-Sensor-Fusion signature (32 bytes hex)",
                        max_length=64,
                    ),
                ),
                (
                    "last_ter_timestamp",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Timestamp of last TER generation (microseconds)",
                        null=True,
                    ),
                ),
                (
                    "htp_session_active",
                    models.BooleanField(
                        default=False, help_text="Active HTP session with validator"
                    ),
                ),
                (
                    "last_htp_heartbeat",
                    models.DateTimeField(
                        blank=True, help_text="Last HTP heartbeat timestamp", null=True
                    ),
                ),
                (
                    "dsm_consensus_participant",
                    models.BooleanField(
                        default=False, help_text="Participating in DSM mesh consensus"
                    ),
                ),
                (
                    "validator_id",
                    models.CharField(
                        blank=True,
                        help_text="Validator managing this edge node",
                        max_length=100,
                    ),
                ),
                (
                    "kyc_verified",
                    models.BooleanField(
                        default=False,
                        help_text="KYC verification status (for validators)",
                    ),
                ),
                (
                    "architecture",
                    models.CharField(
                        choices=[
                            ("x86_64", "x86_64 (Intel/AMD)"),
                            ("arm64", "ARM64 (ARMv8)"),
                        ],
                        default="x86_64",
                        max_length=20,
                    ),
                ),
                ("cpu_model", models.CharField(blank=True, max_length=200)),
                (
                    "cpu_id",
                    models.CharField(
                        blank=True,
                        help_text="CPU serial number for fingerprinting",
                        max_length=200,
                    ),
                ),
                ("cpu_cores", models.IntegerField(blank=True, null=True)),
                ("ram_gb", models.IntegerField(blank=True, null=True)),
                ("storage_gb", models.IntegerField(blank=True, null=True)),
                (
                    "disk_serials",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of disk serial numbers for fingerprinting",
                    ),
                ),
                ("nic_model", models.CharField(blank=True, max_length=200)),
                (
                    "dmi_uuid",
                    models.CharField(
                        blank=True,
                        help_text="DMI/SMBIOS UUID for fingerprinting",
                        max_length=36,
                    ),
                ),
                ("os_version", models.CharField(blank=True, max_length=100)),
                ("hookprobe_version", models.CharField(blank=True, max_length=20)),
                (
                    "deployment_type",
                    models.CharField(
                        choices=[
                            ("edge", "Edge Deployment"),
                            ("cloud", "Cloud Backend"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="edge",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("warning", "Warning"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("uptime_seconds", models.BigIntegerField(default=0)),
                ("cpu_usage_percent", models.FloatField(default=0)),
                ("ram_usage_percent", models.FloatField(default=0)),
                ("disk_usage_percent", models.FloatField(default=0)),
                ("network_rx_bytes", models.BigIntegerField(default=0)),
                ("network_tx_bytes", models.BigIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="devices.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["customer", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Log",
                "verbose_name_plural": "Device Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DeviceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("cpu_usage", models.FloatField()),
                ("ram_usage", models.FloatField()),
                ("disk_usage", models.FloatField()),
                ("network_rx_rate", models.BigIntegerField(default=0)),
                ("network_tx_rate", models.BigIntegerField(default=0)),
                ("qsecbit_score", models.FloatField(blank=True, null=True)),
                ("threat_events_count", models.IntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Metric",
                "verbose_name_plural": "Device Metrics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["customer", "status"], name="devices_dev_custome_3a21b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_id"], name="devices_dev_device__e2c19e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["-last_seen"], name="devices_dev_last_se_0f47ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["hardware_fingerprint"], name="devices_dev_hardwar_98caed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["customer", "-last_seen"], name="devices_dev_custome_552197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicelog",
            index=models.Index(
                fields=["device", "log_type", "-timestamp"],
                name="devices_dev_device__86ab6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicemetric",
            index=models.Index(
                fields=["device", "-timestamp"], name="devices_dev_device__a66dd9_idx"
            ),
        ),
    ]
