# Generated by Django 5.1.15 on 2026-01-20 09:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VPNCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Certificate serial number (hex)",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="Certificate CN (usually user email)", max_length=255
                    ),
                ),
                (
                    "subject_alt_name",
                    models.CharField(
                        blank=True, help_text="SAN for certificate", max_length=255
                    ),
                ),
                (
                    "public_key_pem",
                    models.TextField(help_text="Public key in PEM format"),
                ),
                (
                    "certificate_pem",
                    models.TextField(help_text="X.509 certificate in PEM format"),
                ),
                (
                    "encrypted_private_key",
                    models.BinaryField(help_text="AES-256-GCM encrypted private key"),
                ),
                (
                    "key_encryption_iv",
                    models.BinaryField(
                        help_text="IV for private key encryption", max_length=12
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                            ("pending", "Pending Issuance"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=255)),
                (
                    "fingerprint_sha256",
                    models.CharField(
                        help_text="SHA256 fingerprint of certificate", max_length=64
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Certificate",
                "verbose_name_plural": "VPN Certificates",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="VPNProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly profile name", max_length=100
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("guardian", "Guardian (Travel)"),
                            ("fortress", "Fortress (Home/Business)"),
                        ],
                        default="fortress",
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("macos", "macOS"),
                            ("windows", "Windows"),
                            ("universal", "Universal"),
                        ],
                        default="universal",
                        max_length=20,
                    ),
                ),
                (
                    "vpn_server",
                    models.CharField(
                        help_text="Nexus VPN gateway hostname/IP", max_length=255
                    ),
                ),
                (
                    "vpn_remote_id",
                    models.CharField(
                        help_text="IKEv2 remote identifier", max_length=255
                    ),
                ),
                (
                    "local_identifier",
                    models.CharField(
                        help_text="User's local identifier (email or UUID)",
                        max_length=255,
                    ),
                ),
                (
                    "route_all_traffic",
                    models.BooleanField(
                        default=False,
                        help_text="Route all traffic through VPN (vs split tunnel)",
                    ),
                ),
                (
                    "split_tunnel_routes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of CIDR ranges for split tunneling",
                    ),
                ),
                (
                    "dns_servers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="DNS servers to use when VPN is active",
                    ),
                ),
                (
                    "on_demand_enabled",
                    models.BooleanField(
                        default=True, help_text="Auto-connect on specific networks"
                    ),
                ),
                (
                    "on_demand_rules",
                    models.JSONField(
                        blank=True, default=list, help_text="On-demand connection rules"
                    ),
                ),
                (
                    "bandwidth_limit_mbps",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum bandwidth allocation in Mbps",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Profile expiration (null = no expiry)",
                        null=True,
                    ),
                ),
                (
                    "download_token",
                    models.CharField(
                        help_text="One-time download token", max_length=64, unique=True
                    ),
                ),
                ("download_count", models.IntegerField(default=0)),
                ("last_downloaded", models.DateTimeField(blank=True, null=True)),
                (
                    "max_downloads",
                    models.IntegerField(
                        default=5,
                        help_text="Max profile downloads before regeneration required",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="vpn.vpncertificate",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Target Guardian/Fortress device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_profiles",
                        to="devices.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Profile",
                "verbose_name_plural": "VPN Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VPNSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        help_text="Client's public IP address"
                    ),
                ),
                (
                    "assigned_ip",
                    models.GenericIPAddressField(
                        help_text="IP assigned to client in VPN tunnel"
                    ),
                ),
                (
                    "client_user_agent",
                    models.CharField(
                        blank=True, help_text="Client device/OS info", max_length=255
                    ),
                ),
                (
                    "ike_sa_id",
                    models.CharField(
                        blank=True,
                        help_text="IKE Security Association ID",
                        max_length=64,
                    ),
                ),
                (
                    "child_sa_id",
                    models.CharField(
                        blank=True, help_text="Child SA ID for ESP", max_length=64
                    ),
                ),
                ("bytes_in", models.BigIntegerField(default=0)),
                ("bytes_out", models.BigIntegerField(default=0)),
                ("packets_in", models.BigIntegerField(default=0)),
                ("packets_out", models.BigIntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("avg_latency_ms", models.FloatField(default=0)),
                ("packet_loss_percent", models.FloatField(default=0)),
                (
                    "htp_flow_token",
                    models.CharField(
                        blank=True,
                        help_text="HTP flow token for Nexus→Device tunnel",
                        max_length=32,
                    ),
                ),
                (
                    "htp_session_state",
                    models.CharField(
                        default="init", help_text="HTP session state", max_length=20
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="vpn.vpnprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Session",
                "verbose_name_plural": "VPN Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VPNAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("profile_created", "Profile Created"),
                            ("profile_downloaded", "Profile Downloaded"),
                            ("profile_revoked", "Profile Revoked"),
                            ("session_started", "Session Started"),
                            ("session_ended", "Session Ended"),
                            ("auth_success", "Authentication Success"),
                            ("auth_failed", "Authentication Failed"),
                            ("cert_issued", "Certificate Issued"),
                            ("cert_revoked", "Certificate Revoked"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vpn_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vpn.vpnprofile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vpn.vpnsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Access Log",
                "verbose_name_plural": "VPN Access Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="vpncertificate",
            index=models.Index(
                fields=["user", "status"], name="vpn_vpncert_user_id_6cc423_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpncertificate",
            index=models.Index(
                fields=["serial_number"], name="vpn_vpncert_serial__64cad8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpncertificate",
            index=models.Index(
                fields=["fingerprint_sha256"], name="vpn_vpncert_fingerp_7eb597_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnprofile",
            index=models.Index(
                fields=["user", "is_active"], name="vpn_vpnprof_user_id_ce6075_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnprofile",
            index=models.Index(
                fields=["download_token"], name="vpn_vpnprof_downloa_645299_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnprofile",
            index=models.Index(
                fields=["device", "is_active"], name="vpn_vpnprof_device__3312da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vpnprofile",
            unique_together={("user", "device", "platform")},
        ),
        migrations.AddIndex(
            model_name="vpnsession",
            index=models.Index(
                fields=["profile", "is_active"], name="vpn_vpnsess_profile_811cd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnsession",
            index=models.Index(
                fields=["-started_at"], name="vpn_vpnsess_started_e9b590_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnsession",
            index=models.Index(
                fields=["client_ip"], name="vpn_vpnsess_client__0a501e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnaccesslog",
            index=models.Index(
                fields=["user", "-timestamp"], name="vpn_vpnacce_user_id_08ec70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vpnaccesslog",
            index=models.Index(
                fields=["action", "-timestamp"], name="vpn_vpnacce_action_c16196_idx"
            ),
        ),
    ]
